services:
  rest-api:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - ./:/usr/src/app
      depends_on:
        - postgres

  postgres:
    image: postgres:14.12-alpine
    env_file: ".env.docker"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
volumes:
  postgres_data: